#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

matlab="/usr/local/MATLAB/R2018b/bin/matlab"

matlabplot="$matlab -nodesktop -nosplash -r \"save3DImage; exit;\" | tail -n +11"

eval $matlabplot
